apiVersion: v1
kind: Secret
metadata:
  name: secret-opaque
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://bring:QQp1xlJGjOCAescp@cluster0.qytnb.mongodb.net/<dbname>?retryWrites=true&w=majority
  AWS_S3_BUCKET_NAME: bring
  AWS_SECRET_ACCESS_KEY: px1ewsh7cyJEDgytdkwNlmooGzFTWWdcnbnNIicK
  AWS_ACCESS_KEY_ID: AKIAVNUP74L2XXULNM6R
  TWILIO_SECURE_IDENTIFIER: ACfb98dc826e52221ed6b58bf815fa59fa
  TWILIO_AUTH_TOKEN: ca1afa19bf408079398d91c65cb5041f
  TWILIO_PHONE_NUMBER: "+15412254855"
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
  EMAIL_USER: bringdonationsportal@gmail.com
  EMAIL_PW: bxrbvhplihnipjih
  JWT_AUTH_KEY: 2151A945E26E88F9B7A51347E2F47
  CLIENT_URL: https://bringrecycling.mvpstudio.org
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: bringdonations
