apiVersion: v1
kind: Service
metadata:
  name: bring-recycling-webserver
  namespace: prod-bring-recycling
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000