---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  namespace: prod-bring-recycling
  labels:
    app: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react-client
          image: mvpstudio/bring-server:ReactJan20
          resources:
            limits:
              cpu: 0.1
              memory: 100Mi
            requests:
              cpu: 0.1
              memory: 100Mi
          ports:
            - containerPort: 3000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
